config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  #root 'application#top'
  root 'static_pages#home'
  get 'home'=>'static_pages#home'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def top
    render html: "Top hello, world!"
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    # 一覧表示の処理
    @contacts = Contact.all
  end

  def show
    # 詳細表示の処理
  end

  def new
    # 新規作成フォーム表示の処理
    @contact = Contact.new
  end

  def create
    # 新規作成の処理
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  def edit
    # 編集フォーム表示の処理
  end

  def update
    # 更新の処理
  end

  def destroy
    # 削除の処理
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/index.html.erb
<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.message %></td>
  </tr>
<% end %>

app/views/contacts/new.html.erb
<h1>お問合せ</h1>

<%= form_with(model: @contact, local: true) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
  <%= form.label :message %>
  <%= form.text_field :message %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'お問い合わせ一覧', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DockerCircleciEcsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>24/5:03</p>

<%= link_to 'お問い合わせ', new_contact_path %>